### ISSUE TITLE
patch for cygwin

### ISSUE THREAD

**Issue by matzeri** [sfabbro/suitesparse#1]
Dear Sebastien,
testing your autoconf on cygwin, I needed some changes.
Full patch available here:

http://matzeri.altervista.org/works/suitesparse/
- innocuous typo on "AMD/configure.ac"
- due to case insensitive file system "CHOLMOD/Core" collides with automake "rm -f core" so I renamed "CHOLMOD/Core" to "CHOLMOD/Cored"
-  the tests programs have already a fail code on exit so testing for that exit code is more effective than using diff . On cygwin all the diffs fail as the platform is 32 bit, so memory size does not match.
- on addons/m4/ax_check_pkg_lib.m4 the AC_CHECK_LIB is called without LIBS as they are attached to LDFLAGS. But on windows platforms the order matters and this approach fails. Mine is a just workaround, as I am not fluent on m4, instead of a proper implementation.
- due to Metis License. The default should be without metis.
- SPQR built without tbb

**Comment by sfabbro** [comment]
Thanks for the patch.
I applied most of your proposed changes. For metis, I left it on for testing the package because I want to make sure it passes tests with all options, but left off for default at configure time. I applied the CHOLMOD change from Core to Cored as a hook.

Feel free to to pull requests as well.
